name: Build Agenda Page

on:
  # Runs the workflow every day at midnight UTC
  schedule:
    - cron: '0 0 * * *'  # This cron expression triggers the action every day at midnight UTC
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Choose the appropriate Node.js version

    - name: Install dependencies
      run: |
        npm install  # Install dependencies (if needed, e.g., fs, path, etc.)

    - name: Generate HTML for Agenda
      run: |
        node ./generateAgenda.js  # Run a script to generate the agenda page

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add agenda/index.html || true  # Add the agenda file, if present
        git commit -m "Update agenda page [skip ci]" || echo "No changes to commit"
        git push origin HEAD:${{ github.ref_name }} || echo "Nothing to push"
        cat agenda/index.html || echo "Agenda file not found"
